### ISSUE TITLE
Cannot present image in other tab exclude "Popular"

### ISSUE THREAD

**Issue by oldtrafford91** [naoyashiga/Dunk#2]
When trying to select image in other tab exclude "Popular", it does nothing and appear warning in console:

```
2016-01-07 23:05:00.346 DribbbleReader[11241:237339] Warning: Attempt to present <DribbbleReader.ImageModalViewController: 0x7f8d83e11f80> on <UINavigationController: 0x7f8d84051000> whose view is not in the window hierarchy!
```

**Comment by oldtrafford91** [comment]
Solved. Add these line in `BaseViewController.swift` after adding view from pageMenu:

```
self.addChildViewController(pageMenu!)
pageMenu?.didMoveToParentViewController(self)
```

In `ShotCollectionViewController.swift`, use `parentViewController` instead of `parentNavigationController` to present `ImageModalViewController`:

```
parentViewController?.presentViewController(vc, animated: true, completion: nil)
```

Should remove property `parentNavigationController` too.

**Comment by naoyashiga** [comment]
Thank you for comment and pull request.

I will close this issue.
